#NECESITO UNA LISTA DE 1,2,3,...E,F...DG ASI = [0,0,0,0....,40,0,0]

#DEFINIR ID_PARTIDA

#QUE ME LLAME A LA FUNCION DE GUARDAR_PARTIDA CUANDO PONGO UN NOMBRE QUE NO EXISTE DE PARTIDA

#LISTA DE JUGADORES

#MODIFICAR EN TIRO: CUANDO TERMINE DE TIRAR QUE ME QUEDE UNA LISTA COMO LA QUE MARQUE QUE NECESITO AL PRINCIPIO. ESA LISTA LA VOY A UTILIZAR PARA ARMAR
#EL TABLERO, SE TIENE QUE ARMAR DESDE LA BASE DE DATOS, POR AHORA ESTA GUARDADA EN EL SISTEMA Y LO NECESITO EN LA MEMORIA LOS PUNTAJES QUE VAN OBTENIENDO
#LOS JUGADORES, DE ESA FORMA CUANDO REANUDO UNA PARTIDA PUEDO VOLVER A ARMAR LA TABLA DE PUNTAJES, SINO SE PIERDE
#SE VA A TENER QUE MODIFICAR EL TABLERO PARA ESTO.

#CUANDO SE INGRESA LOS JUGADORES SE DEBE GUARDAR SU NOMBRE


